services:
  api:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    container_name: homelab-playground-api-dev
    ports:
      - "8080:8080"

  ui-dev:
    build:
      context: ../..
      dockerfile: docker/ui/Dockerfile.dev
    container_name: homelab-playground-ui-dev
    ports:
      - "5173:5173"
    depends_on:
      - api